# Generated by Django 3.2.3 on 2022-01-09 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cathegory',
            new_name='category',
        ),
    ]
